apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-web
spec:
  replicas: 1
  selector:
    matchLabels:
      component: portafolio-web
  template:
    metadata:
      labels:
        component: portafolio-web
    spec:
      containers:
        - name: portafolio-front
          image: 